/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type ArchiveItem = {
  _id: string;
  _type: "archiveItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  category:
    | "photographs"
    | "historicalDocuments"
    | "familyStories"
    | "oralHistories"
    | "videos"
    | "audioArchive";
  year?: number;
  location?: string;
  person?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  externalUrl?: string;
  description?: LocaleText;
};

export type LocaleText = {
  _type: "localeText";
  el: string;
  en: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type LocaleString = {
  _type: "localeString";
  el: string;
  en: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug: Slug;
  date: string;
  time?: string;
  location?: LocaleString;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: LocaleText;
  isUpcoming?: boolean;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug: Slug;
  publishedAt: string;
  category: "announcement" | "event" | "community" | "culture";
  excerpt?: LocaleText;
  content?: LocaleBlockContent;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type LocaleBlockContent = {
  _type: "localeBlockContent";
  el?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  en?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: {
    title?: LocaleString;
    description?: LocaleText;
  };
  heading?: LocaleString;
  intro?: LocaleText;
  address?: LocaleString;
  mapEmbedUrl?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: LocaleString;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: {
    title?: LocaleString;
    description?: LocaleText;
  };
  email?: string;
  phone?: string;
  address?: LocaleString;
  socialLinks?: {
    facebook?: string;
    instagram?: string;
    youtube?: string;
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: {
    title?: LocaleString;
    description?: LocaleText;
  };
  hero?: {
    title?: LocaleString;
    tagline?: LocaleString;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    primaryCta?: {
      label?: LocaleString;
      href?: string;
    };
    secondaryCta?: {
      label?: LocaleString;
      href?: string;
    };
  };
  welcome?: {
    heading?: LocaleString;
    text?: LocaleBlockContent;
    ctaLabel?: LocaleString;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SanityFileAssetReference
  | ArchiveItem
  | LocaleText
  | SanityImageCrop
  | SanityImageHotspot
  | LocaleString
  | Event
  | Slug
  | News
  | LocaleBlockContent
  | ContactPage
  | SiteSettings
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    siteTitle,    logo,    seo,    email,    phone,    address,    socialLinks  }
export type SiteSettingsQueryResult = {
  siteTitle: LocaleString | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo: {
    title?: LocaleString;
    description?: LocaleText;
  } | null;
  email: string | null;
  phone: string | null;
  address: LocaleString | null;
  socialLinks: {
    facebook?: string;
    instagram?: string;
    youtube?: string;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0] {    seo,    hero,    welcome  }
export type HomePageQueryResult = {
  seo: {
    title?: LocaleString;
    description?: LocaleText;
  } | null;
  hero: {
    title?: LocaleString;
    tagline?: LocaleString;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    primaryCta?: {
      label?: LocaleString;
      href?: string;
    };
    secondaryCta?: {
      label?: LocaleString;
      href?: string;
    };
  } | null;
  welcome: {
    heading?: LocaleString;
    text?: LocaleBlockContent;
    ctaLabel?: LocaleString;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: contactPageQuery
// Query: *[_type == "contactPage"][0] {    seo,    heading,    intro,    address,    mapEmbedUrl  }
export type ContactPageQueryResult = {
  seo: {
    title?: LocaleString;
    description?: LocaleText;
  } | null;
  heading: LocaleString | null;
  intro: LocaleText | null;
  address: LocaleString | null;
  mapEmbedUrl: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: allNewsQuery
// Query: *[_type == "news"] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    publishedAt,    category,    excerpt,    image  }
export type AllNewsQueryResult = Array<{
  _id: string;
  title: LocaleString | null;
  slug: string;
  publishedAt: string;
  category: "announcement" | "community" | "culture" | "event";
  excerpt: LocaleText | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: newsBySlugQuery
// Query: *[_type == "news" && slug.current == $slug][0] {    title,    publishedAt,    category,    excerpt,    content,    image  }
export type NewsBySlugQueryResult = {
  title: LocaleString | null;
  publishedAt: string;
  category: "announcement" | "community" | "culture" | "event";
  excerpt: LocaleText | null;
  content: LocaleBlockContent | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: newsSlugsQuery
// Query: *[_type == "news" && defined(slug.current)].slug.current
export type NewsSlugsQueryResult = Array<string>;

// Source: src/sanity/queries.ts
// Variable: upcomingEventsQuery
// Query: *[_type == "event" && isUpcoming == true] | order(date asc) {    _id,    title,    "slug": slug.current,    date,    time,    location,    image,    description  }
export type UpcomingEventsQueryResult = Array<{
  _id: string;
  title: LocaleString | null;
  slug: string;
  date: string;
  time: string | null;
  location: LocaleString | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: LocaleText | null;
}>;

// Source: src/sanity/queries.ts
// Variable: pastEventsQuery
// Query: *[_type == "event" && isUpcoming == false] | order(date desc) {    _id,    title,    "slug": slug.current,    date,    time,    location,    image,    description  }
export type PastEventsQueryResult = Array<{
  _id: string;
  title: LocaleString | null;
  slug: string;
  date: string;
  time: string | null;
  location: LocaleString | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: LocaleText | null;
}>;

// Source: src/sanity/queries.ts
// Variable: eventBySlugQuery
// Query: *[_type == "event" && slug.current == $slug][0] {    title,    date,    time,    location,    image,    description,    isUpcoming  }
export type EventBySlugQueryResult = {
  title: LocaleString | null;
  date: string;
  time: string | null;
  location: LocaleString | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: LocaleText | null;
  isUpcoming: boolean | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: archiveItemsQuery
// Query: *[_type == "archiveItem"] | order(year desc) {    _id,    title,    category,    year,    location,    person,    image,    file,    externalUrl,    description  }
export type ArchiveItemsQueryResult = Array<{
  _id: string;
  title: LocaleString | null;
  category:
    | "audioArchive"
    | "familyStories"
    | "historicalDocuments"
    | "oralHistories"
    | "photographs"
    | "videos";
  year: number | null;
  location: string | null;
  person: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  file: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  } | null;
  externalUrl: string | null;
  description: LocaleText | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0] {\n    siteTitle,\n    logo,\n    seo,\n    email,\n    phone,\n    address,\n    socialLinks\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "homePage"][0] {\n    seo,\n    hero,\n    welcome\n  }\n': HomePageQueryResult;
    '\n  *[_type == "contactPage"][0] {\n    seo,\n    heading,\n    intro,\n    address,\n    mapEmbedUrl\n  }\n': ContactPageQueryResult;
    '\n  *[_type == "news"] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    category,\n    excerpt,\n    image\n  }\n': AllNewsQueryResult;
    '\n  *[_type == "news" && slug.current == $slug][0] {\n    title,\n    publishedAt,\n    category,\n    excerpt,\n    content,\n    image\n  }\n': NewsBySlugQueryResult;
    '\n  *[_type == "news" && defined(slug.current)].slug.current\n': NewsSlugsQueryResult;
    '\n  *[_type == "event" && isUpcoming == true] | order(date asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    time,\n    location,\n    image,\n    description\n  }\n': UpcomingEventsQueryResult;
    '\n  *[_type == "event" && isUpcoming == false] | order(date desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    time,\n    location,\n    image,\n    description\n  }\n': PastEventsQueryResult;
    '\n  *[_type == "event" && slug.current == $slug][0] {\n    title,\n    date,\n    time,\n    location,\n    image,\n    description,\n    isUpcoming\n  }\n': EventBySlugQueryResult;
    '\n  *[_type == "archiveItem"] | order(year desc) {\n    _id,\n    title,\n    category,\n    year,\n    location,\n    person,\n    image,\n    file,\n    externalUrl,\n    description\n  }\n': ArchiveItemsQueryResult;
  }
}
